In [4]:
! pip install np

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for np: filename=np-1.0.2-py3-none-any.whl size=13676 sha256=c0d6332b62f7f8631d31e3ef2e1b4f2be1193636163b09fc73c3073b21a4c896
  Stored in directory: /root/.cache/pip/wheels/8d/31/5b/f3f27c678f2b3ad7e29903ed09bb7446717fd4c8b35f53973a
Successfully built np


In [5]:
import numpy as np

In [6]:
agelist =[23,28,11,18,34]
age_list =np.array(list)
print(agelist)

[23, 28, 11, 18, 34]


In [7]:
np.random.randint(2,10)

7

In [8]:
evn_num=np.arange(start=10,stop=100,step=2)
print(evn_num)
type(evn_num)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


numpy.ndarray

In [9]:
nums=np.linspace(start=1,stop=100,num=10)
print(nums)


[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [10]:
np.ones(1)

array([1.])

In [11]:
matrix=np.empty((3,3),dtype=int)
print(matrix)

[[           22662800                  36                   0]
 [                  0                   0 7005406607063736886]
 [3761681506585961773 3258465588949640292 3546413420678571057]]


In [12]:
matrix = np.full((3,3),fill_value=11)
print(matrix)

[[11 11 11]
 [11 11 11]
 [11 11 11]]


In [13]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
books=np.array([("learn Python","Data Science Journal","Scala for Data Science"),(20,23,18)])
print("Shape of the array is",books.shape)

Shape of the array is (2, 3)


In [15]:
employee = np.array([("Charles",18),("Logan",20),("Jessica",34)])
print("Created array:",employee)
employee_reshaped = employee.reshape(6,1)
print("\nReshaped array:",employee_reshaped)

Created array: [['Charles' '18']
 ['Logan' '20']
 ['Jessica' '34']]

Reshaped array: [['Charles']
 ['18']
 ['Logan']
 ['20']
 ['Jessica']
 ['34']]


In [16]:
! pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [17]:
import numpy as np

In [18]:
age_list=[23,28,11,18,34]
age_array=np.array(age_list)
print(age_array)
type(age_array)

[23 28 11 18 34]


numpy.ndarray

In [19]:
books=np.array(['Learn Python','Data Science Journal','Scala For Data Science'])
print(books)
type(books)

['Learn Python' 'Data Science Journal' 'Scala For Data Science']


numpy.ndarray

In [20]:
np.random.random(size=20)

array([0.3895239 , 0.26835787, 0.35492151, 0.0457091 , 0.11359538,
       0.79540041, 0.41424229, 0.66995615, 0.02274169, 0.29499358,
       0.63268876, 0.13623198, 0.82362191, 0.24309164, 0.44077079,
       0.65328637, 0.67703106, 0.53128641, 0.22919233, 0.18021959])

In [21]:
np.random.rand(2,3)

array([[0.14433895, 0.03824263, 0.34477835],
       [0.22177176, 0.46042375, 0.70399889]])

In [22]:
np.random.randn(2,3)

array([[ 0.57606285, -2.07798784, -0.29406138],
       [-0.38527705,  1.00047779,  1.51074731]])

In [23]:
np.random.randint(2,10)

3

In [24]:
np.random.randint(10,100,10)

array([70, 25, 88, 58, 15, 85, 75, 45, 90, 93])

In [25]:
even_numbers=np.arange(start=10,stop=100,step=2)
print(even_numbers)
type(even_numbers)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


numpy.ndarray

In [26]:
even_numbers=np.arange(start=10,stop=100,step=2)
print(even_numbers)
type(even_numbers)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


numpy.ndarray

In [27]:
nums=np.linspace(start=1,stop=100,num=10)
print(nums)
type(nums)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


numpy.ndarray

In [28]:
nums=np.linspace(start=1,stop=100,num=10)
print(nums)
type(nums)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


numpy.ndarray

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
matrix=np.empty((3,3),dtype=int)
print(matrix)

[[           22662800                  36                   0]
 [                  0                   0 7005406607063736886]
 [3761681506585961773 3258465588949640292 3546413420678571057]]


In [32]:

matrix=np.full((3,3),fill_value=11)
print(matrix)

[[11 11 11]
 [11 11 11]
 [11 11 11]]


In [33]:
matrix=np.full((2,2),fill_value=5)
print(matrix)

[[5 5]
 [5 5]]


In [34]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(N=4,M=5,k=0)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [37]:
np.eye(N=4,M=5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.eye(N=4,M=5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [39]:
np.eye(N=4,M=5,k=3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
np.eye(N=4,M=5,k=4)

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
np.eye(N=4,M=5,k=5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
np.eye(N=4,M=5,k=6)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
np.eye(N=4,M=5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [44]:
np.eye(N=4,M=5,k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [45]:
np.eye(N=4,M=5,k=-3)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [46]:
books=np.array([('Learn Python','Data Science Journal','Scada for Data Science'),(20,23,28)])
print('Shape of the array is:',books.shape)

Shape of the array is: (2, 3)


In [47]:
books=np.array([('Learn Python','Data Science Journal','Scada for Data Science'),(20,23,28)])
print('Shape of the array is:',books.size)

Shape of the array is: 6


In [48]:
books=np.array([('Learn Python','Data Science Journal','Scada for Data Science','Python For Machine Learning'),(15,20,23,28)])
print('Shape of the array is:',books.shape)

Shape of the array is: (2, 4)


In [49]:
books=np.array([('Learn Python','Data Science Journal','Scada for Data Science','Python For Machine Learning'),(15,20,23,28)])
print('Shape of the array is:',books.size)

Shape of the array is: 8


In [50]:
weight_age=np.array([(3.2,5.5,7.3),(1,2.3,6.1)])
print('Number of element in array:',weight_age.dtype)

Number of element in array: float64


In [51]:
books=np.array([('Learn Python','Data Science Journal','Scada for Data Science'),(20,23,28)])
print('Shape of the array is:',books.ndim)

Shape of the array is: 2


In [52]:
books=np.array([('Learn Python',20),('Data Science Journal',23),('Scada for Data Science',28)])
print('Created array is:',books)
books_reshape=books.reshape(6,1)
print('\nreshape books:',books_reshape)

Created array is: [['Learn Python' '20']
 ['Data Science Journal' '23']
 ['Scada for Data Science' '28']]

reshape books: [['Learn Python']
 ['20']
 ['Data Science Journal']
 ['23']
 ['Scada for Data Science']
 ['28']]


In [54]:
names=np.array([('Rahul',28),('Laxmi',28),('Deepak',34)])
print('Created array:',names)
names_reshape=names.reshape(6,1)
print('\nreshape names:',names_reshape)

Created array: [['Rahul' '28']
 ['Laxmi' '28']
 ['Deepak' '34']]

reshape names: [['Rahul']
 ['28']
 ['Laxmi']
 ['28']
 ['Deepak']
 ['34']]


In [55]:
names=np.array([('Rahul',28),('Laxmi',28),('Deepak',34),('Bablu',31),('Sikandar',26),('Phunnan',33)])
print('Created array:',names)
names_reshape=names.reshape(12,1)
print('\nreshape names:',names_reshape)

Created array: [['Rahul' '28']
 ['Laxmi' '28']
 ['Deepak' '34']
 ['Bablu' '31']
 ['Sikandar' '26']
 ['Phunnan' '33']]

reshape names: [['Rahul']
 ['28']
 ['Laxmi']
 ['28']
 ['Deepak']
 ['34']
 ['Bablu']
 ['31']
 ['Sikandar']
 ['26']
 ['Phunnan']
 ['33']]


In [56]:
names=np.array([('Rahul',28),('Laxmi',28),('Deepak',34),('Bablu',31),('Sikandar',26),('Phunnan',33)])
print('name in last element:',names[-1])

name in last element: ['Phunnan' '33']


In [57]:
names=np.array([('Rahul',28),('Laxmi',28),('Deepak',34),('Bablu',31),('Sikandar',26),('Phunnan',33)])
print('Element at position 1:',names[1])

Element at position 1: ['Laxmi' '28']


In [58]:
names[0][1]

'28'

In [59]:
names[0],[-1]

(array(['Rahul', '28'], dtype='<U21'), [-1])

In [60]:
weight=np.array([50,43,56,48,55.5,76,82,65])
print('4th and 5th Element"',weight[3:5])

4th and 5th Element" [48.  55.5]


In [61]:
weight=np.array([50,43,56,48,55.5,76,82,65])
print('7th and 8th Element"',weight[5:7])

7th and 8th Element" [76. 82.]


In [62]:
weight=np.array([50,43,56,48,55.5,76,82,65])
print('2nd and 3rd Element"',weight[1:3])

2nd and 3rd Element" [43. 56.]


In [63]:
weight=np.array([50,43,56,48,55.5,76,82,65])
print('Every 3rd Element:',weight[0::3])

Every 3rd Element: [50. 48. 82.]


In [64]:
weight=np.array([50,43,56,48,55.5,76,82,65])
print('Every 6th Element:',weight[1::6])

Every 6th Element: [43. 65.]


In [65]:
weight=np.array([50,43,56,48,55.5,76,82,65])
print('Element Before 76:',weight[:5])

Element Before 76: [50.  43.  56.  48.  55.5]


In [66]:
weight=np.array([50,43,56,48,55.5,76,82,65])
print('7th and 8th Element"',weight[5:7])
print('Every 3rd Element:',weight[0::3])
print('Element Before 76:',weight[:5])



7th and 8th Element" [76. 82.]
Every 3rd Element: [50. 48. 82.]
Element Before 76: [50.  43.  56.  48.  55.5]


In [67]:
age=np.array([(54,92,14,25),(68,19,28,32)])
print('\nElements in 1st row and 1st three column:',age[0,0:3])


Elements in 1st row and 1st three column: [54 92 14]


In [68]:
age=np.array([(54,92,14,25),(68,19,28,32)])
print('\nElements in 2nd row and 2nd and 4th column:',age[1,1:])


Elements in 2nd row and 2nd and 4th column: [19 28 32]


In [69]:
rahul=np.array([(85,75,54,32,68,95)])
print('\nElement in 1st row and 1st three column:',rahul[0,0:4])


Element in 1st row and 1st three column: [85 75 54 32]


In [70]:
#Arithmetic Opearator
odd_nums=np.array([3,7,5,9])
print('odd nums:',odd_nums)
evn_nums=np.array([8,10,4,2])
print('even_nums:',evn_nums)
sum=odd_nums+evn_nums
print('addition:',sum)
sub=odd_nums-evn_nums
print('substraction:',sub)


odd nums: [3 7 5 9]
even_nums: [ 8 10  4  2]
addition: [11 17  9 11]
substraction: [-5 -3  1  7]


In [71]:
nums=np.array([3,7,5,9])
print('New Numbers:',nums*2)

New Numbers: [ 6 14 10 18]


In [72]:
m1=np.array([[1,0,2],[4,-2,3]])
m2=np.array([[4,0,1],[2,3,0]])
prod=m1*m2
print('Element-wise Multiplication:\n',prod)


Element-wise Multiplication:
 [[ 4  0  2]
 [ 8 -6  0]]


In [73]:
m1=np.array([[2,3,5],[5,6,9]])
m2=np.array([[6,5,3],[5,4,6]])
prod=m1*m2
print('Element wise Multiplication:\n',prod)

Element wise Multiplication:
 [[12 15 15]
 [25 24 54]]


In [74]:
#Mareix Multiplication
m1=np.array([[1,0,2],[4,-2,3]])
m2=np.array([[4,0],[2,3],[1,4]])
multi=m1.dot(m2)
print('Matrix Multiplication:\n',multi)

Matrix Multiplication:
 [[ 6  8]
 [15  6]]


In [75]:
salary=np.array([20000,50000,60000,15000,250000,36000])
print('Maximum salary in array:',salary.min())

Maximum salary in array: 15000


In [ ]:
salary=np.array([20000,50000,60000,15000,250000,36000])
print('Maximum salary in array:',salary.max())

In [ ]:
salary=np.array([20000,50000,60000,15000,250000,36000])
print('Maximum salary in array:',salary.var())

In [76]:
salary=np.array([20000,50000,60000,15000,250000,36000])
print('Maximum salary in array:',salary.std())

Maximum salary in array: 81200.198412456


In [77]:
side=np.array([20,50,60,15,25,36])
print('Area of side:',np.square(side))

Area of side: [ 400 2500 3600  225  625 1296]


In [78]:
side=np.array([20,50,60,15,25,36])
print('Volume of side:',np.power(side,3))

Volume of side: [  8000 125000 216000   3375  15625  46656]


In [79]:
data_scientists=([('Rahul',25),('Laxmi',35),('Umesh',45)])
print('\nOriginal Matrix:',data_scientists)
print('\ntranspose:',np.transpose(data_scientists))


Original Matrix: [('Rahul', 25), ('Laxmi', 35), ('Umesh', 45)]

transpose: [['Rahul' 'Laxmi' 'Umesh']
 ['25' '35' '45']]
